// <auto-generated />
using System;
using CODE_CDIO4.Models;
using CODE_CDIO4.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CODE_CDIO4.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);
            modelBuilder.Entity("CODE_CDIO4.Models.GioHang", b =>
            {
                b.Property<int>("Id_NguoiMua")
                    .HasColumnType("int")
                    .HasColumnName("id_nguoimua");

                b.Property<int>("Id_TacPham")
                    .HasColumnType("int")
                    .HasColumnName("id_tacpham");

                b.Property<DateTime>("NgayThem")
                    .HasColumnType("datetime2")
                    .HasColumnName("ngaythem");

                b.Property<string>("Loai")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)")
                    .HasColumnName("loai");

                b.HasKey("Id_NguoiMua", "Id_TacPham");

                b.HasIndex("Id_TacPham");

                b.HasOne("CODE_CDIO4.Models.NguoiDung", "NguoiMua")
                    .WithMany("GioHangs")
                    .HasForeignKey("Id_NguoiMua")
                    .OnDelete(DeleteBehavior.Cascade);

                b.HasOne("CODE_CDIO4.Models.TacPham", "TacPham")
                    .WithMany("GioHangs")
                    .HasForeignKey("Id_TacPham")
                    .OnDelete(DeleteBehavior.Cascade);

                b.Navigation("NguoiMua");
                b.Navigation("TacPham");

                b.ToTable("GIOHANG");
            });


            modelBuilder.Entity("CODE_CDIO4.Models.BinhLuan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Id_NguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("id_nguoidung");

                    b.Property<int>("Id_TacPham")
                        .HasColumnType("int")
                        .HasColumnName("id_tacpham");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngaytao");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noidung");

                    b.HasKey("Id");

                    b.HasIndex("Id_NguoiDung");

                    b.HasIndex("Id_TacPham");

                    b.ToTable("BINHLUAN");
                });

            modelBuilder.Entity("CODE_CDIO4.Models.CamXuc", b =>
                {
                    b.Property<int>("Id_NguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("id_nguoidung");

                    b.Property<int>("Id_TacPham")
                        .HasColumnType("int")
                        .HasColumnName("id_tacpham");

                    b.Property<string>("CamXucValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id_NguoiDung", "Id_TacPham");

                    b.HasIndex("Id_TacPham");

                    b.ToTable("CAMXUC");
                });

            modelBuilder.Entity("CODE_CDIO4.Models.DanhGia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Diem")
                        .HasColumnType("int");

                    b.Property<int>("Id_NguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("id_nguoidung");

                    b.Property<int>("Id_TacPham")
                        .HasColumnType("int")
                        .HasColumnName("id_tacpham");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Id_NguoiDung");

                    b.HasIndex("Id_TacPham");

                    b.ToTable("DANHGIA");
                });

            modelBuilder.Entity("CODE_CDIO4.Models.DonHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("GiamGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Id_NguoiMua")
                        .HasColumnType("int")
                        .HasColumnName("id_nguoimua");

                    b.Property<DateTime>("NgayMua")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id_NguoiMua");

                    b.ToTable("DONHANG");
                });

            modelBuilder.Entity("CODE_CDIO4.Models.DonHang_ChiTiet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Id_DonHang")
                        .HasColumnType("int")
                        .HasColumnName("id_donhang");

                    b.Property<int>("Id_TacPham")
                        .HasColumnType("int")
                        .HasColumnName("id_tacpham");

                    b.Property<int?>("id_donhang")
                        .HasColumnType("int");

                    b.Property<int?>("id_tacpham")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id_DonHang");

                    b.HasIndex("Id_TacPham");

                    b.ToTable("DONHANG_CHITIET", t =>
                        {
                            t.Property("id_donhang")
                                .HasColumnName("id_donhang1");

                            t.Property("id_tacpham")
                                .HasColumnName("id_tacpham1");
                        });
                });

            modelBuilder.Entity("CODE_CDIO4.Models.DuAnCongDong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Id_QuanLy")
                        .HasColumnType("int")
                        .HasColumnName("id_quanly");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mota");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngaytao");

                    b.Property<string>("TenDuAn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenduan");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("trangthai");

                    b.HasKey("Id");

                    b.HasIndex("Id_QuanLy");

                    b.ToTable("DUANCONGDONG");
                });

            modelBuilder.Entity("CODE_CDIO4.Models.DuAn_TacPham", b =>
                {
                    b.Property<int>("Id_DuAn")
                        .HasColumnType("int")
                        .HasColumnName("id_duan");

                    b.Property<int>("Id_TacPham")
                        .HasColumnType("int")
                        .HasColumnName("id_tacpham");

                    b.HasKey("Id_DuAn", "Id_TacPham");

                    b.HasIndex("Id_TacPham");

                    b.ToTable("DUAN_TACPHAM");
                });

            modelBuilder.Entity("CODE_CDIO4.Models.GioHang", b =>
                {
                    b.Property<int>("Id_NguoiMua")
                        .HasColumnType("int")
                        .HasColumnName("id_nguoimua");

                    b.Property<int>("Id_TacPham")
                        .HasColumnType("int")
                        .HasColumnName("id_tacpham");

                    b.Property<DateTime>("NgayThem")
                        .HasColumnType("datetime2");

                    b.HasKey("Id_NguoiMua", "Id_TacPham");

                    b.HasIndex("Id_TacPham");

                    b.ToTable("GIOHANG");
                });

            modelBuilder.Entity("CODE_CDIO4.Models.Hashtag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ten");

                    b.HasKey("Id");

                    b.ToTable("HASHTAGS");
                });

            modelBuilder.Entity("CODE_CDIO4.Models.MauSac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ten");

                    b.HasKey("Id");

                    b.ToTable("MAUSAC");
                });

            modelBuilder.Entity("CODE_CDIO4.Models.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapDo")
                        .HasColumnType("int")
                        .HasColumnName("capdo");

                    b.Property<int>("DiemThuong")
                        .HasColumnType("int")
                        .HasColumnName("diemthuong");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("matkhau");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngaytao");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("role");

                    b.Property<string>("Sdt")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("sdt");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ten");

                    b.HasKey("Id");

                    b.ToTable("NGUOIDUNG");
                });

            modelBuilder.Entity("CODE_CDIO4.Models.TacPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DuongDan")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("duongdan");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gia");

                    b.Property<int?>("Id_MauSac")
                        .HasColumnType("int")
                        .HasColumnName("id_mausac");

                    b.Property<int>("Id_NguoiTao")
                        .HasColumnType("int")
                        .HasColumnName("id_nguoitao");

                    b.Property<int?>("Id_TheLoai")
                        .HasColumnType("int")
                        .HasColumnName("id_theloai");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mota");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngaytao");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("trangthai");

                    b.HasKey("Id");

                    b.HasIndex("Id_MauSac");

                    b.HasIndex("Id_NguoiTao");

                    b.HasIndex("Id_TheLoai");

                    b.ToTable("TACPHAM");
                });

            modelBuilder.Entity("CODE_CDIO4.Models.TacPham_Hashtags", b =>
                {
                    b.Property<int>("Id_TacPham")
                        .HasColumnType("int")
                        .HasColumnName("id_tacpham");

                    b.Property<int>("Id_Hashtag")
                        .HasColumnType("int")
                        .HasColumnName("id_hashtag");

                    b.HasKey("Id_TacPham", "Id_Hashtag");

                    b.HasIndex("Id_Hashtag");

                    b.ToTable("TACPHAM_HASHTAGS");
                });

            modelBuilder.Entity("CODE_CDIO4.Models.ThamGiaDuAn", b =>
                {
                    b.Property<int>("Id_DuAn")
                        .HasColumnType("int")
                        .HasColumnName("id_duan");

                    b.Property<int>("Id_NguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("id_nguoidung");

                    b.Property<DateTime>("NgayThamGia")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngaythamgia");

                    b.Property<string>("VaiTro")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vaitro");

                    b.HasKey("Id_DuAn", "Id_NguoiDung");

                    b.HasIndex("Id_NguoiDung");

                    b.ToTable("THAMGIADUAN");
                });

            modelBuilder.Entity("CODE_CDIO4.Models.ThanhToan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Id_DonHang")
                        .HasColumnType("int")
                        .HasColumnName("id_donhang");

                    b.Property<DateTime>("NgayTT")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngaytt");

                    b.Property<string>("PhuongThuc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("phuongthuc");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("trangthai");

                    b.HasKey("Id");

                    b.HasIndex("Id_DonHang");

                    b.ToTable("THANHTOAN");
                });

            modelBuilder.Entity("CODE_CDIO4.Models.TheLoai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten");

                    b.HasKey("Id");

                    b.ToTable("THELOAI");
                });

            modelBuilder.Entity("CODE_CDIO4.Models.ThongBao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DaDoc")
                        .HasColumnType("bit")
                        .HasColumnName("dadoc");

                    b.Property<int>("Id_NguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("id_nguoidung");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngaytao");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noidung");

                    b.HasKey("Id");

                    b.HasIndex("Id_NguoiDung");

                    b.ToTable("THONGBAO");
                });

            modelBuilder.Entity("CODE_CDIO4.Models.BinhLuan", b =>
                {
                    b.HasOne("CODE_CDIO4.Models.NguoiDung", "NguoiDung")
                        .WithMany("BinhLuans")
                        .HasForeignKey("Id_NguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CODE_CDIO4.Models.TacPham", "TacPham")
                        .WithMany("BinhLuans")
                        .HasForeignKey("Id_TacPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("TacPham");
                });

            modelBuilder.Entity("CODE_CDIO4.Models.CamXuc", b =>
                {
                    b.HasOne("CODE_CDIO4.Models.NguoiDung", "NguoiDung")
                        .WithMany("CamXucs")
                        .HasForeignKey("Id_NguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CODE_CDIO4.Models.TacPham", "TacPham")
                        .WithMany("CamXucs")
                        .HasForeignKey("Id_TacPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("TacPham");
                });

            modelBuilder.Entity("CODE_CDIO4.Models.DanhGia", b =>
                {
                    b.HasOne("CODE_CDIO4.Models.NguoiDung", "NguoiDung")
                        .WithMany("DanhGias")
                        .HasForeignKey("Id_NguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CODE_CDIO4.Models.TacPham", "TacPham")
                        .WithMany()
                        .HasForeignKey("Id_TacPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("TacPham");
                });

            modelBuilder.Entity("CODE_CDIO4.Models.DonHang", b =>
                {
                    b.HasOne("CODE_CDIO4.Models.NguoiDung", "NguoiMua")
                        .WithMany("DonHangs")
                        .HasForeignKey("Id_NguoiMua")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiMua");
                });

            modelBuilder.Entity("CODE_CDIO4.Models.DonHang_ChiTiet", b =>
                {
                    b.HasOne("CODE_CDIO4.Models.DonHang", "DonHang")
                        .WithMany("DonHang_ChiTiets")
                        .HasForeignKey("Id_DonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CODE_CDIO4.Models.TacPham", "TacPham")
                        .WithMany("DonHang_ChiTiets")
                        .HasForeignKey("Id_TacPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("TacPham");
                });

            modelBuilder.Entity("CODE_CDIO4.Models.DuAnCongDong", b =>
                {
                    b.HasOne("CODE_CDIO4.Models.NguoiDung", "QuanLy")
                        .WithMany("DuAnQuanLy")
                        .HasForeignKey("Id_QuanLy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuanLy");
                });

            modelBuilder.Entity("CODE_CDIO4.Models.DuAn_TacPham", b =>
                {
                    b.HasOne("CODE_CDIO4.Models.DuAnCongDong", "DuAn")
                        .WithMany("DuAn_TacPhams")
                        .HasForeignKey("Id_DuAn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CODE_CDIO4.Models.TacPham", "TacPham")
                        .WithMany("DuAn_TacPhams")
                        .HasForeignKey("Id_TacPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DuAn");

                    b.Navigation("TacPham");
                });

            modelBuilder.Entity("CODE_CDIO4.Models.GioHang", b =>
                {
                    b.HasOne("CODE_CDIO4.Models.NguoiDung", "NguoiMua")
                        .WithMany("GioHangs")
                        .HasForeignKey("Id_NguoiMua")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CODE_CDIO4.Models.TacPham", "TacPham")
                        .WithMany("GioHangs")
                        .HasForeignKey("Id_TacPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiMua");

                    b.Navigation("TacPham");
                });

            modelBuilder.Entity("CODE_CDIO4.Models.TacPham", b =>
                {
                    b.HasOne("CODE_CDIO4.Models.MauSac", "MauSac")
                        .WithMany("TacPhams")
                        .HasForeignKey("Id_MauSac");

                    b.HasOne("CODE_CDIO4.Models.NguoiDung", "NguoiTao")
                        .WithMany("TacPhams")
                        .HasForeignKey("Id_NguoiTao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CODE_CDIO4.Models.TheLoai", "TheLoai")
                        .WithMany("TacPhams")
                        .HasForeignKey("Id_TheLoai");

                    b.Navigation("MauSac");

                    b.Navigation("NguoiTao");

                    b.Navigation("TheLoai");
                });

            modelBuilder.Entity("CODE_CDIO4.Models.TacPham_Hashtags", b =>
                {
                    b.HasOne("CODE_CDIO4.Models.Hashtag", "Hashtag")
                        .WithMany("TacPham_hashtags")
                        .HasForeignKey("Id_Hashtag")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CODE_CDIO4.Models.TacPham", "TacPham")
                        .WithMany("TacPham_Hashtags")
                        .HasForeignKey("Id_TacPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hashtag");

                    b.Navigation("TacPham");
                });

            modelBuilder.Entity("CODE_CDIO4.Models.ThamGiaDuAn", b =>
                {
                    b.HasOne("CODE_CDIO4.Models.DuAnCongDong", "DuAnCongDong")
                        .WithMany("ThamGiaDuAns")
                        .HasForeignKey("Id_DuAn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CODE_CDIO4.Models.NguoiDung", "NguoiDung")
                        .WithMany("ThamGiaDuAns")
                        .HasForeignKey("Id_NguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DuAnCongDong");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("CODE_CDIO4.Models.ThanhToan", b =>
                {
                    b.HasOne("CODE_CDIO4.Models.DonHang", "DonHang")
                        .WithMany("ThanhToans")
                        .HasForeignKey("Id_DonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");
                });

            modelBuilder.Entity("CODE_CDIO4.Models.ThongBao", b =>
                {
                    b.HasOne("CODE_CDIO4.Models.NguoiDung", "NguoiDung")
                        .WithMany("ThongBaos")
                        .HasForeignKey("Id_NguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("CODE_CDIO4.Models.DonHang", b =>
                {
                    b.Navigation("DonHang_ChiTiets");

                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("CODE_CDIO4.Models.DuAnCongDong", b =>
                {
                    b.Navigation("DuAn_TacPhams");

                    b.Navigation("ThamGiaDuAns");
                });

            modelBuilder.Entity("CODE_CDIO4.Models.Hashtag", b =>
                {
                    b.Navigation("TacPham_hashtags");
                });

            modelBuilder.Entity("CODE_CDIO4.Models.MauSac", b =>
                {
                    b.Navigation("TacPhams");
                });

            modelBuilder.Entity("CODE_CDIO4.Models.NguoiDung", b =>
                {
                    b.Navigation("BinhLuans");

                    b.Navigation("CamXucs");

                    b.Navigation("DanhGias");

                    b.Navigation("DonHangs");

                    b.Navigation("DuAnQuanLy");

                    b.Navigation("GioHangs");

                    b.Navigation("TacPhams");

                    b.Navigation("ThamGiaDuAns");

                    b.Navigation("ThongBaos");
                });

            modelBuilder.Entity("CODE_CDIO4.Models.TacPham", b =>
                {
                    b.Navigation("BinhLuans");

                    b.Navigation("CamXucs");

                    b.Navigation("DonHang_ChiTiets");

                    b.Navigation("DuAn_TacPhams");

                    b.Navigation("GioHangs");

                    b.Navigation("TacPham_Hashtags");
                });

            modelBuilder.Entity("CODE_CDIO4.Models.TheLoai", b =>
                {
                    b.Navigation("TacPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
